name: Continuous Integration

on:
  push:
    branches:
      - main
env:
  DEFAULT_APP_TAG: hello-world-app
  IMAGE_VERSION: v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Source Code
        uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9' 

      - name: Install Development Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements_dev.txt
      
      - name: Run Linter
        run: ./build/app-lint.sh
      
      - name: Run Tests
        run: ./build/app-tests.sh
      
      - name: Build Python App w/Dependencies
        run: ./build/app-build.sh

      - name: Run App (see pipeline logs)
        run: ./build/app-run.sh
      
      - uses: docker/setup-buildx-action@v3
      - name: Build App Container w/Docker
        run: ./build/docker-build-container.sh ${{ env.DEFAULT_APP_TAG }}:${{ env.IMAGE_VERSION }}

      - name: Docker Image Scan with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: '${{ env.DEFAULT_APP_TAG }}:${{ env.IMAGE_VERSION }}'

      - name: Run App Container (see pipeline logs)
        run: ./build/docker-run-container.sh ${{ env.DEFAULT_APP_TAG }}:${{ env.IMAGE_VERSION }}

      # Publish Artifacts
      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          overwrite: true
          retention-days: 1
          name: HelloWorldApp
          path: |
            'out/requirements.txt'
            'out/src'